---
# ------------------------------------------------------------------------------
# Lab 06:
# Site-to-Site Virtual Private Network: Connect OCI resources to on-premises via
# site-to-site VPN, using LibreSwan as the customer premises equipment
# 
# Launch On-Premises Network and CPE VM in Ashburn Region
#
# In this practice, you will simulate an on-premises network (OPN) in the Ashburn
# region with a VCN, and a compute instance that will run LibreSwan for the CPE
# router. There will be a second VM for pinging purposes.
# ------------------------------------------------------------------------------

- name:                       "Create a VCN in Ashburn"
  oracle.oci.oci_network_vcn:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    display_name:             "IAD-NP-LAB06-OPN-01"
    key_by:
      - "display_name"
    cidr_blocks:
      -                       "{{ ashburn_cidr }}"
    dns_label:                "iadnplab06vcn01"
    state:                    "present"
  register:                   iad_np_lab06_opn_01

- name:                       "Display Ashburn VCN Configuration"
  ansible.builtin.debug:
    var:                      iad_np_lab06_opn_01.vcn
    verbosity:                1

# ------------------------------------------------------------------------------
# Attach Gateways to VCN
# ------------------------------------------------------------------------------

- name:                       "Create Internet Gateway in Ashburn"
  oracle.oci.oci_network_internet_gateway:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    key_by:
      - "display_name"
    vcn_id:                   "{{ iad_np_lab06_opn_01.vcn.id }}"
    display_name:             "IAD-NP-LAB06-IG-01"
    is_enabled:               true
    state:                    "present"
  register:                   iad_np_lab06_ig_01

# ------------------------------------------------------------------------------
# Route tables
# ------------------------------------------------------------------------------

- name:                       "Update Default Route Table for ASHBURN VCN"
  oracle.oci.oci_network_route_table:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    display_name:             "IAD-NP-LAB06-RT-01"
    route_rules:
      - destination:          "0.0.0.0/0"
        destination_type:     "CIDR_BLOCK"
        network_entity_id:    "{{ iad_np_lab06_ig_01.internet_gateway.id }}"
    rt_id:                    "{{ iad_np_lab06_opn_01.vcn.default_route_table_id }}"
    state:                    "present"
  register:                   iad_np_lab06_rt_01

# ------------------------------------------------------------------------------
# DHCP Options
# ------------------------------------------------------------------------------

- name:                       "Create DHCP Options for Ashburn"
  oracle.oci.oci_network_dhcp_options:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    key_by:
      - "display_name"
    dhcp_id:                  "{{ iad_np_lab06_opn_01.vcn.default_dhcp_options_id }}"
    display_name:             "IAD-NP-LAB06-DHCP-01"
    options:
      - type:                 "DomainNameServer"
        server_type:          "VcnLocalPlusInternet"
      - type:                 "SearchDomain"
        search_domain_names:
          - "iadnplab06vcn01.oraclevcn.com"
    state:                    "present"
  register:                   iad_np_lab06_dhcp_01

# ------------------------------------------------------------------------------
# Security lists (aka Firewall Rules)
# ------------------------------------------------------------------------------

- name:                       "Update Ashburn Default Security List"
  oracle.oci.oci_network_security_list:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    key_by:
      - "display_name"
    display_name:             "IAD-NP-LAB06-SL-01"
    security_list_id:         "{{ iad_np_lab06_opn_01.vcn.default_security_list_id }}"
    vcn_id:                   "{{ iad_np_lab06_opn_01.vcn.id }}"
    state:                    "present"
    egress_security_rules:
      - description:          "Allow all outbound traffic"
        destination:          "0.0.0.0/0"
        destination_type:     "CIDR_BLOCK"
        protocol:             "all"
        is_stateless:         "false"
    ingress_security_rules:
      - description:          "Allow all inbound SSH traffic"
        protocol:             "6"
        source:               "0.0.0.0/0"
        source_type:          "CIDR_BLOCK"
        is_stateless:         "false"
        tcp_options:
          destination_port_range:
            max:              "22"
            min:              "22"
      - description:          "Destination Unreachable - Fragmentation Needed and Don't Fragment was Set"
        icmp_options:
          code:               "4"
          type:               "3"
        protocol:             "1"
        source:               "0.0.0.0/0"
        source_type:          "CIDR_BLOCK"
        is_stateless:         "false"
      - description:          "Destination Unreachable"
        icmp_options:
          type:               "3"
        protocol:             "1"
        source:               "{{ ashburn_cidr }}"
        source_type:          "CIDR_BLOCK"
        is_stateless:         "false"
      - description:          "Allow all PINGs from Phoenix VCN"
        icmp_options:
          type:               "8"
        protocol:             "1"
        source:               "{{ phoenix_cidr }}"
        source_type:          "CIDR_BLOCK"
        is_stateless:         "false"

- name:                       "Create Ashburn Private Subnet security List"
  oracle.oci.oci_network_security_list:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    key_by:
      - "display_name"
    display_name:             "IAD-NP-LAB06-SL-02"
    vcn_id:                   "{{ iad_np_lab06_opn_01.vcn.id }}"
    state:                    "present"
    egress_security_rules:
      - description:          "Allow all outbound traffic"
        destination:          "0.0.0.0/0"
        destination_type:     "CIDR_BLOCK"
        protocol:             "all"
        is_stateless:         "false"
    ingress_security_rules:
      - description:          "Allow pings from Phoenix VCN"
        icmp_options:
          type:               "8"
        source:               "{{ phoenix_cidr }}"
        source_type:          "CIDR_BLOCK"
        is_stateless:         "false"
        protocol:             "1"
  register:                   iad_np_lab06_sl_02

# ------------------------------------------------------------------------------
# Create Public Subnet in Ashburn VCN
# ------------------------------------------------------------------------------

- name:                       "Calculate Ashburn IPv4 subnet CIDRs"
  ansible.builtin.set_fact:
    ashburn_public_cidr:      "{{ ashburn_cidr | ansible.utils.ipsubnet(25, 0) }}"
    ashburn_private_cidr:     "{{ ashburn_cidr | ansible.utils.ipsubnet(25, 1) }}"

- name:                       "Create Ashburn Public Subnet"
  oracle.oci.oci_network_subnet:
    region:                   "us-ashburn-1"
    key_by:
      - "display_name"
    compartment_id:           "{{ compartment_id }}"
    display_name:             "IAD-NP-LAB06-SNET-01"
    cidr_block:               "{{ ashburn_public_cidr }}"
    prohibit_public_ip_on_vnic: false
    prohibit_internet_ingress: false
    vcn_id:                   "{{ iad_np_lab06_opn_01.vcn.id }}"
    state:                    "present"
    dns_label:                "public"
  register:                   iad_np_lab06_snet_01

# ------------------------------------------------------------------------------
# Create Private Subnet in Ashburn.
#
# Note: There is a circular dependendcy between the private subnet and its route
#       table. To overcome this, the subnet is created using the VCN default
#       table. Later on, the subnet is updated with the correct route table.
#
#       In order to preserve idempotency, the first reference to the subnet has
#       to reference differing route tables. First time throught, the VCN
#       default route table is used if the subnet route table does not exist
#       yet. On subsequent runs, the subnet route table is used.
#
#       This approach requires a second call to oci_network_subnet later in the
#       playbook after the route table is created.
# ------------------------------------------------------------------------------

- name:                       "Check for Ashburn Private Subnet Route Table"
  oracle.oci.oci_network_route_table_facts:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    display_name:             "IAD-NP-LAB06-RT-02"
  register:                   iad_np_lab06_rt_02

- name:                       "Get Route Table OCID for Ashburn Private Subnet"
  ansible.builtin.set_fact:
    ashburn_private_rt_id:    "{{ iad_np_lab06_rt_02.route_tables[0].id }}"
  when:
    - iad_np_lab06_rt_02.route_tables | length > 0

- name:                       "Get Route Table OCID for Ashburn VCN"
  ansible.builtin.set_fact:
    ashburn_private_rt_id:    "{{ iad_np_lab06_opn_01.vcn.default_route_table_id }}"
  when:
    - iad_np_lab06_rt_02.route_tables | length == 0
  
- name:                       "Create Ashburn Private Subnet"
  oracle.oci.oci_network_subnet:
    region:                   "us-ashburn-1"
    compartment_id:           "{{ compartment_id }}"
    key_by:
      - "display_name"
    display_name:             "IAD-NP-LAB06-SNET-02"
    cidr_block:               "{{ ashburn_private_cidr }}"
    prohibit_public_ip_on_vnic: true
    prohibit_internet_ingress: true
    vcn_id:                   "{{ iad_np_lab06_opn_01.vcn.id }}"
    security_list_ids:
      - "{{ iad_np_lab06_sl_02.security_list.id }}"
    state:                    "present"
    dns_label:                "private"
    route_table_id:           "{{ ashburn_private_rt_id }}"
  register:                   iad_np_lab06_snet_02
...
