---
# ------------------------------------------------------------------------------
# Lab 05:
# Design and Implement a Real-Network Architecture: Configuring private DNS
# Zones, views, resolvers, listeners and forwarder
#
# Virtual Cloud Network 01
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Private DNS Zone
# ------------------------------------------------------------------------------

- name:                             "Get ZONE A DNS View Details"
  oracle.oci.oci_dns_view_facts:
    region:                         "{{ region }}"
    compartment_id:                 "{{ compartment_id }}"
    scope:                          "PRIVATE"
    display_name:                   "{{ vcn_01.vcn.display_name }}"
  register:                         vcn01_views

- name:                             "Display Current ZONE A DNS View Details"
  ansible.builtin.debug:
    var:                            vcn01_views
    verbosity:                      1

- name:                             "Extract DNS View ID"
  ansible.builtin.set_fact:
    vcn01_view_id:                  "{{ vcn01_views.views[0].id }}"
  when:
    - vcn01_views.views | length != 0

- name:                             "Create ZONE A DNS View"
  oracle.oci.oci_dns_view:
    region:                         "{{ region }}"
    compartment_id:                 "{{ compartment_id }}"
    scope:                          "PRIVATE"
    display_name:                   "{{ vcn_01.vcn.display_name }}"
  register:                         vcn01_view
  when:
    - vcn01_views.views | length == 0

- name:                             "Extract DNS View ID"
  ansible.builtin.set_fact:
    vcn01_view_id:                  vcn01_view.view.id
  when:
    - vcn01_view.view.id is defined

- name:                             "Display ZONE A DNS OCID"
  ansible.builtin.debug:
    var:                            vcn01_view_id
    verbosity:                      1
  when:
    - vcn01_view_id is defined

- name:                             "Check for Existance of DNS Zone"
  oracle.oci.oci_dns_zone_facts:
    region:                         "{{ region }}"
    compartment_id:                 "{{ compartment_id }}"
    name:                           "zone-a.local"
    scope:                          "PRIVATE"
    view_id:                        "{{ vcn01_view_id }}"
  register:                         zone_a_exists

- name:                             "Create DNS Zone"
  oracle.oci.oci_dns_zone:
    region:                         "{{ region }}"
    compartment_id:                 "{{ compartment_id }}"
    name:                           "zone-a.local"
    scope:                          "PRIVATE"
    view_id:                        "{{ vcn01_view_id }}"
    zone_type:                      "PRIMARY"
    state:                          "present"
  when:
    - zone_a_exists.zones | length == 0

- name:                             "Get Details about DNS Zone"
  oracle.oci.oci_dns_zone_facts:
    region:                         "{{ region }}"
    compartment_id:                 "{{ compartment_id }}"
    name:                           "zone-a.local"
    scope:                          "PRIVATE"
    view_id:                        "{{ vcn01_view_id }}"
  register:                         zone_a

- name:                             "Display ZONE A Details"
  ansible.builtin.debug:
    var:                            zone_a.zones
    verbosity:                      1
  when:
    - zone_a.zones is defined

- name:                             "Retrieve all Zone A Records"
  oracle.oci.oci_dns_zone_records_facts:
    region:                         "{{ region }}"
    compartment_id:                 "{{ compartment_id }}"
    zone_name_or_id:                "{{ zone_a.zones[0].id }}"
    scope:                          "PRIVATE"
    view_id:                        "{{ vcn01_view_id }}"
  register:                         zone_a_records

- name:                             "Display ZONE A Records"
  ansible.builtin.debug:
    var:                            zone_a_records
    verbosity:                      1

- name:                             "Add DNS Entry for ZONE A"
  oracle.oci.oci_dns_rrset:
    region:                         "{{ region }}"
    compartment_id:                 "{{ compartment_id }}"
    domain:                         "server01.zone-a.local"
    rtype:                          "A"
    scope:                          "PRIVATE"
    state:                          "present"
    view_id:                        "{{ vcn01_view_id }}"
    zone_name_or_id:                "{{ zone_a.zones[0].id }}"
    patch_items:
      - domain:                     "server01.zone-a.local"
        operation:                  "ADD"
        rdata:                      "10.0.0.2"
        rtype:                      "A"
        ttl:                        30
...